# Generated by Django 5.1.2 on 2026-04-21 19:15

import ckeditor.fields
import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('portfolio', '0001_initial'), ('portfolio', '0002_remove_personalinfo_twitter_and_more'), ('portfolio', '0003_banner'), ('portfolio', '0004_alter_personalinfo_logo_alter_personalinfo_pdfcv_and_more'), ('portfolio', '0005_remove_project_image_project_main_image_projectimage'), ('portfolio', '0006_rename_main_image_project_image'), ('portfolio', '0007_project_github_link'), ('portfolio', '0008_alter_banner_image'), ('portfolio', '0009_alter_banner_image'), ('portfolio', '0010_alter_banner_image'), ('portfolio', '0011_alter_banner_alt_text_alter_banner_image_and_more'), ('portfolio', '0012_alter_personalinfo_pdfcv'), ('portfolio', '0013_alter_personalinfo_photo'), ('portfolio', '0014_alter_personalinfo_photo'), ('portfolio', '0015_project_pdfcv'), ('portfolio', '0016_project_created_date'), ('portfolio', '0017_remove_project_tech_stack_technology'), ('portfolio', '0018_delete_skill'), ('portfolio', '0019_skill'), ('portfolio', '0020_personalinfo_skills_background_image'), ('portfolio', '0021_contactsubmission'), ('portfolio', '0022_personalinfo_spinner_image'), ('portfolio', '0023_alter_banner_page'), ('portfolio', '0024_remove_personalinfo_logo'), ('portfolio', '0025_bannerimages'), ('portfolio', '0026_alter_bannerimages_background_and_more'), ('portfolio', '0027_alter_bannerimages_background_and_more'), ('portfolio', '0028_alter_banner_image_alter_banner_page_and_more'), ('portfolio', '0029_alter_banner_options_alter_bannerimages_options_and_more')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-start_date'],
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='project_image')),
                ('github_link', models.URLField(blank=True, null=True)),
                ('pdfCV', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='pdf_documentation')),
                ('created_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_date'],
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home'), ('skills', 'Skills'), ('contact', 'Contact')], max_length=20, unique=True)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Banner_Image')),
                ('alt_text', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
            },
        ),
        migrations.CreateModel(
            name='BannerImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='background')),
                ('fog_7', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='fog_7')),
                ('mountain_10', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='mountain_10')),
                ('mountain_9', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='mountain_9')),
                ('mountain_8', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='mountain_8')),
                ('fog_5', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='fog_5')),
                ('mountain_7', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='mountain_7')),
                ('mountain_6', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='mountain_6')),
                ('fog_4', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='fog_4')),
                ('mountain_5', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='mountain_5')),
                ('fog_3', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='fog_3')),
                ('mountain_4', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='mountain_4')),
                ('mountain_3', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='mountain_3')),
                ('fog_2', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='fog_2')),
                ('mountain_2', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='mountain_2')),
                ('mountain_1', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='mountain_1')),
                ('sun_rays', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='sun_rays')),
                ('black_shadow', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='black_shadow')),
                ('fog_1', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='fog_1')),
            ],
            options={
                'verbose_name': 'Banner Images',
                'verbose_name_plural': 'Banner Images',
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
            },
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('photo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='photo')),
                ('birthdate', models.DateField()),
                ('job_title', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('about', ckeditor.fields.RichTextField()),
                ('pdfCV', cloudinary.models.CloudinaryField(max_length=255, verbose_name='pdf')),
                ('availability', models.CharField(choices=[('available', 'Available'), ('not_available', 'Not Available')], default='available', max_length=20)),
                ('skills_background_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='skills_background_image')),
                ('spinner_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='spinner_image')),
            ],
            options={
                'verbose_name': 'Personal Info',
                'verbose_name_plural': 'Personal Info',
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='ProjectImage')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.project')),
            ],
            options={
                'verbose_name': 'Project Image',
                'verbose_name_plural': 'Project Images',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='portfolio.project')),
            ],
            options={
                'verbose_name': 'Technology',
                'verbose_name_plural': 'Technologies',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, max_length=200, null=True)),
                ('feedback', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Testimonial_Image')),
                ('date_given', models.DateField()),
            ],
            options={
                'ordering': ['-date_given'],
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
    ]
