# Generated by Django 5.1.2 on 2024-10-19 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='website',
        ),
    ]
