# Generated by Django 5.1.2 on 2024-10-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_personalinfo_twitter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('projects', 'Projects'), ('skills', 'Skills'), ('contact', 'Contact')], max_length=20, unique=True)),
                ('image', models.ImageField(upload_to='banners/')),
                ('alt_text', models.CharField(help_text='Alternative text for the banner image', max_length=255)),
            ],
        ),
    ]
