# Generated by Django 5.1.2 on 2024-10-20 14:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='logo',
            field=models.ImageField(upload_to='media/logo/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='pdfCV',
            field=models.FileField(upload_to='media/pdfs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='PDF CV'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='photo',
            field=models.ImageField(upload_to='media/images/', verbose_name='Profile Picture'),
        ),
    ]
