# Generated by Django 5.1.2 on 2024-10-22 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_remove_project_image_project_main_image_projectimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='main_image',
            new_name='image',
        ),
    ]
