# Generated by Django 5.1.2 on 2024-10-24 21:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_banner_alt_text_alter_banner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='pdfCV',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='pdf'),
        ),
    ]
