# Generated by Django 5.1.2 on 2024-10-24 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_alter_personalinfo_pdfcv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
