# Generated by Django 5.1.2 on 2024-10-24 21:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_alter_personalinfo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
