# Generated by Django 5.1.2 on 2024-10-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_project_pdfcv'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
