# Generated by Django 5.1.2 on 2024-10-25 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_remove_project_tech_stack_technology'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
