# Generated by Django 5.1.2 on 2024-10-25 13:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='skills_background_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
