# Generated by Django 5.1.2 on 2024-10-26 10:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_contactsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='spinner_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
