# Generated by Django 5.1.2 on 2024-10-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_personalinfo_spinner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('projects', 'Projects'), ('skills', 'Skills'), ('contact', 'Contact')], max_length=20, unique=True),
        ),
    ]
