# Generated by Django 5.1.2 on 2024-10-27 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_alter_banner_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='logo',
        ),
    ]
