# Generated by Django 5.1.2 on 2024-11-11 14:44

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0024_remove_personalinfo_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('fog_7', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('mountain_10', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('mountain_9', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('mountain_8', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('fog_5', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('mountain_7', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('mountain_6', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('fog_4', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('mountain_5', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('fog_3', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('mountain_4', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('mountain_3', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('fog_2', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('mountain_2', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('mountain_1', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('sun_rays', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('black_shadow', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('fog_1', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
        ),
    ]
