# Generated by Django 5.1.2 on 2024-11-11 15:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0026_alter_bannerimages_background_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerimages',
            name='background',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='background'),
        ),
        migrations.AlterField(
            model_name='bannerimages',
            name='black_shadow',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='black_shadow'),
        ),
        migrations.AlterField(
            model_name='bannerimages',
            name='fog_1',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='fog_1'),
        ),
        migrations.AlterField(
            model_name='bannerimages',
            name='fog_2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='fog_2'),
        ),
        migrations.AlterField(
            model_name='bannerimages',
            name='fog_3',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='fog_3'),
        ),
        migrations.AlterField(
            model_name='bannerimages',
            name='fog_4',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='fog_4'),
        ),
        migrations.AlterField(
            model_name='bannerimages',
            name='fog_5',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='fog_5'),
        ),
        migrations.AlterField(
            model_name='bannerimages',
            name='fog_7',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='fog_7'),
        ),
        migrations.AlterField(
            model_name='bannerimages',
            name='mountain_1',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='mountain_1'),
        ),
        migrations.AlterField(
            model_name='bannerimages',
            name='mountain_10',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='mountain_10'),
        ),
        migrations.AlterField(
            model_name='bannerimages',
            name='mountain_2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='mountain_2'),
        ),
        migrations.AlterField(
            model_name='bannerimages',
            name='mountain_3',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='mountain_3'),
        ),
        migrations.AlterField(
            model_name='bannerimages',
            name='mountain_4',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='mountain_4'),
        ),
        migrations.AlterField(
            model_name='bannerimages',
            name='mountain_5',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='mountain_5'),
        ),
        migrations.AlterField(
            model_name='bannerimages',
            name='mountain_6',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='mountain_6'),
        ),
        migrations.AlterField(
            model_name='bannerimages',
            name='mountain_7',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='mountain_7'),
        ),
        migrations.AlterField(
            model_name='bannerimages',
            name='mountain_8',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='mountain_8'),
        ),
        migrations.AlterField(
            model_name='bannerimages',
            name='mountain_9',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='mountain_9'),
        ),
        migrations.AlterField(
            model_name='bannerimages',
            name='sun_rays',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='sun_rays'),
        ),
    ]
