# Generated by Django 5.1.2 on 2026-04-21 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0028_alter_banner_image_alter_banner_page_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Banner', 'verbose_name_plural': 'Banners'},
        ),
        migrations.AlterModelOptions(
            name='bannerimages',
            options={'verbose_name': 'Banner Images', 'verbose_name_plural': 'Banner Images'},
        ),
        migrations.AlterModelOptions(
            name='contactsubmission',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Contact Submission', 'verbose_name_plural': 'Contact Submissions'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-start_date'], 'verbose_name': 'Experience', 'verbose_name_plural': 'Experiences'},
        ),
        migrations.AlterModelOptions(
            name='personalinfo',
            options={'verbose_name': 'Personal Info', 'verbose_name_plural': 'Personal Info'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['created_date'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='projectimage',
            options={'verbose_name': 'Project Image', 'verbose_name_plural': 'Project Images'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name'], 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.AlterModelOptions(
            name='technology',
            options={'verbose_name': 'Technology', 'verbose_name_plural': 'Technologies'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['-date_given'], 'verbose_name': 'Testimonial', 'verbose_name_plural': 'Testimonials'},
        ),
    ]
